version: "3.9"

services:
  app:
    build:
      context: .
    restart: unless-stopped
    container_name: dsc_dashboard_app
    image: dsc_dashboard_app:0.2.0
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static-data:/home/user/vol/web
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: dsc_dashboard_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  nginx:
    build: ./nginx
    restart: unless-stopped
    container_name: dsc_dashboard_nginx
    image: dsc_dashboard_nginx:0.2.0
    volumes:
      - static-data:/vol/static
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  mongodb-data:
    driver: local
  static-data:
    driver: local