version: "3.9"

services:
  app:
    build:
      context: .
    restart: unless-stopped
    container_name: dsc-dashboard-app
    image: dsc-dashboard-app:1.0.0
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static-data:/home/user/vol/web
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: dsc-dashboard-mysqldb
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ${MYSQL_USER} --password=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysqldb-data:/var/lib/mysql

  nginx:
    build: ./nginx
    restart: unless-stopped
    container_name: dsc-dashboard-nginx
    image: dsc-dashboard-nginx:1.0.0
    volumes:
      - static-data:/vol/static
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  mysqldb-data:
    driver: local
  static-data:
    driver: local