# Generated by Django 3.2.15 on 2022-10-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default=' ', max_length=120),
            preserve_default=False,
        ),
    ]
