version: "3.9"

services:
  app:
    build:
      context: ../
      dockerfile: ./dsc_dev/Dockerfile
    container_name: dsc-dashboard-app
    image: dsc-dashboard-app:1.0.0
    command: >
      sh -c "sed -i 's/import dash_html_components as html/from dash import html/g' ../venv/lib/python3.10/site-packages/dash_bootstrap_components/_table.py
             python manage.py makemigrations
             python manage.py migrate accounts --noinput
             python manage.py migrate admin --noinput
             python manage.py migrate auth --noinput
             python manage.py migrate contenttypes --noinput
             python manage.py migrate sessions --noinput
             python manage.py migrate django_plotly_dash --noinput
             python manage.py migrate tickets --noinput
             python manage.py migrate
             python manage.py wait_for_db
             python manage.py default_users --superuser=yes --username=$DJANGO_SUPERUSER_USERNAME --email=$DJANGO_SUPERUSER_EMAIL --password=$DJANGO_SUPERUSER_PASSWORD
             python manage.py migrate django_plotly_dash --noinput
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - ../dsc_dashboard:/home/user/app
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build:
      context: ../
      dockerfile: ./mysql/Dockerfile
    restart: unless-stopped
    container_name: dsc-dashboard-mysqldb
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ${MYSQL_USER} --password=${MYSQL_PASSWORD}
      interval: 10s
      retries: 10
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysqldb-data:/var/lib/mysql

volumes:
  mysqldb-data:
    driver: local
